<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="Assassin like enemy - all animations" tilewidth="220" tileheight="96" tilecount="96" columns="12">
 <image source="C:/kyrgyz_epos_game/assets/tiles/map/prisonSet/Characters/Assassin like enemy/Assassin like enemy - all animations.png" width="2640" height="768"/>
 <tile id="0" type="assassin"/>
 <tile id="1" type="assassin"/>
 <tile id="2" type="assassin"/>
 <tile id="3" type="assassin"/>
 <tile id="4" type="assassin"/>
 <tile id="5" type="assassin"/>
 <tile id="6" type="assassin"/>
 <tile id="7" type="assassin"/>
 <tile id="8" type="assassin"/>
 <tile id="9" type="assassin"/>
 <tile id="10" type="assassin"/>
 <tile id="11" type="assassin"/>
 <tile id="12" type="assassin"/>
 <tile id="13" type="assassin"/>
 <tile id="14" type="assassin"/>
 <tile id="15" type="assassin"/>
 <tile id="16" type="assassin"/>
 <tile id="17" type="assassin"/>
 <tile id="18" type="assassin"/>
 <tile id="19" type="assassin"/>
 <tile id="20" type="assassin"/>
 <tile id="21" type="assassin"/>
 <tile id="22" type="assassin"/>
 <tile id="23" type="assassin"/>
 <tile id="24" type="assassin"/>
 <tile id="25" type="assassin"/>
 <tile id="26" type="assassin"/>
 <tile id="27" type="assassin"/>
 <tile id="28" type="assassin"/>
 <tile id="29" type="assassin"/>
 <tile id="30" type="assassin"/>
 <tile id="31" type="assassin"/>
 <tile id="32" type="assassin"/>
 <tile id="33" type="assassin"/>
 <tile id="34" type="assassin"/>
 <tile id="35" type="assassin"/>
 <tile id="36" type="assassin"/>
 <tile id="37" type="assassin"/>
 <tile id="38" type="assassin"/>
 <tile id="39" type="assassin"/>
 <tile id="40" type="assassin"/>
 <tile id="41" type="assassin"/>
 <tile id="42" type="assassin"/>
 <tile id="43" type="assassin"/>
 <tile id="44" type="assassin"/>
 <tile id="45" type="assassin"/>
 <tile id="46" type="assassin"/>
 <tile id="47" type="assassin"/>
 <tile id="48" type="assassin"/>
 <tile id="49" type="assassin"/>
 <tile id="50" type="assassin"/>
 <tile id="51" type="assassin"/>
 <tile id="52" type="assassin"/>
 <tile id="53" type="assassin"/>
 <tile id="54" type="assassin"/>
 <tile id="55" type="assassin"/>
 <tile id="56" type="assassin"/>
 <tile id="57" type="assassin"/>
 <tile id="58" type="assassin"/>
 <tile id="59" type="assassin"/>
 <tile id="60" type="assassin"/>
 <tile id="61" type="assassin"/>
 <tile id="62" type="assassin"/>
 <tile id="63" type="assassin"/>
 <tile id="64" type="assassin"/>
 <tile id="65" type="assassin"/>
 <tile id="66" type="assassin"/>
 <tile id="67" type="assassin"/>
 <tile id="68" type="assassin"/>
 <tile id="69" type="assassin"/>
 <tile id="70" type="assassin"/>
 <tile id="71" type="assassin"/>
 <tile id="72" type="assassin"/>
 <tile id="73" type="assassin"/>
 <tile id="74" type="assassin"/>
 <tile id="75" type="assassin"/>
 <tile id="76" type="assassin"/>
 <tile id="77" type="assassin"/>
 <tile id="78" type="assassin"/>
 <tile id="79" type="assassin"/>
 <tile id="80" type="assassin"/>
 <tile id="81" type="assassin"/>
 <tile id="82" type="assassin"/>
 <tile id="83" type="assassin"/>
 <tile id="84" type="assassin"/>
 <tile id="85" type="assassin"/>
 <tile id="86" type="assassin"/>
 <tile id="87" type="assassin"/>
 <tile id="88" type="assassin"/>
 <tile id="89" type="assassin"/>
 <tile id="90" type="assassin"/>
 <tile id="91" type="assassin"/>
 <tile id="92" type="assassin"/>
 <tile id="93" type="assassin"/>
 <tile id="94" type="assassin"/>
 <tile id="95" type="assassin"/>
</tileset>
