<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="Atlas-PropsGrass2_1" tilewidth="32" tileheight="32" tilecount="3520" columns="44">
 <image source="tiles/map/grassLand2/Props/Static props/Atlas-Props-sheet1.png" width="1408" height="2560"/>
 <tile id="45" type="high"/>
 <tile id="46" type="high"/>
 <tile id="47" type="high"/>
 <tile id="48" type="high"/>
 <tile id="49" type="high"/>
 <tile id="50" type="high"/>
 <tile id="51" type="high"/>
 <tile id="52" type="high"/>
 <tile id="53" type="high"/>
 <tile id="54" type="high"/>
 <tile id="55" type="high"/>
 <tile id="56" type="high"/>
 <tile id="57" type="high"/>
 <tile id="58" type="high"/>
 <tile id="59" type="high"/>
 <tile id="60" type="high"/>
 <tile id="177" type="high"/>
 <tile id="178" type="high"/>
 <tile id="179" type="high"/>
 <tile id="180" type="high"/>
 <tile id="181" type="high"/>
 <tile id="182" type="high"/>
 <tile id="183" type="high"/>
 <tile id="184" type="high"/>
 <tile id="185" type="high"/>
 <tile id="186" type="high"/>
 <tile id="187" type="high"/>
 <tile id="188" type="high"/>
 <tile id="189" type="high"/>
 <tile id="190" type="high"/>
 <tile id="191" type="high"/>
 <tile id="192" type="high"/>
 <tile id="309" type="high"/>
 <tile id="310" type="high"/>
 <tile id="311" type="high"/>
 <tile id="312" type="high"/>
 <tile id="313" type="high"/>
 <tile id="314" type="high"/>
 <tile id="315" type="high"/>
 <tile id="316" type="high"/>
 <tile id="317" type="high"/>
 <tile id="318" type="high"/>
 <tile id="319" type="high"/>
 <tile id="320" type="high"/>
 <tile id="321" type="high"/>
 <tile id="322" type="high"/>
 <tile id="323" type="high"/>
 <tile id="324" type="high"/>
 <tile id="441" type="high"/>
 <tile id="442" type="high"/>
 <tile id="443" type="high"/>
 <tile id="444" type="high"/>
 <tile id="445" type="high"/>
 <tile id="446" type="high"/>
 <tile id="447" type="high"/>
 <tile id="448" type="high"/>
 <tile id="449" type="high"/>
 <tile id="450" type="high"/>
 <tile id="451" type="high"/>
 <tile id="452" type="high"/>
 <tile id="453" type="high"/>
 <tile id="454" type="high"/>
 <tile id="455" type="high"/>
 <tile id="456" type="high"/>
 <tile id="575" type="high"/>
 <tile id="576" type="high"/>
 <tile id="577" type="high"/>
 <tile id="578" type="high"/>
 <tile id="579" type="high"/>
 <tile id="580" type="high"/>
 <tile id="2222" type="high"/>
 <tile id="2223" type="high"/>
 <tile id="2224" type="high"/>
 <tile id="2225" type="high"/>
 <tile id="2226" type="high"/>
 <tile id="2227" type="high"/>
 <tile id="2228" type="high"/>
 <tile id="2229" type="high"/>
 <tile id="2230" type="high"/>
 <tile id="2231" type="high"/>
 <tile id="2232" type="high"/>
</tileset>
