<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="giant statues-sword-1" tilewidth="32" tileheight="32" tilecount="80" columns="8">
 <image source="tiles/map/ancientLand/Props/giant statues-sword-1.png" width="256" height="320"/>
 <tile id="1" type="high"/>
 <tile id="2" type="high"/>
 <tile id="3" type="high"/>
 <tile id="4" type="high"/>
 <tile id="5" type="high"/>
 <tile id="6" type="high"/>
 <tile id="7" type="high"/>
 <tile id="9" type="high"/>
 <tile id="10" type="high"/>
 <tile id="11" type="high"/>
 <tile id="12" type="high"/>
 <tile id="13" type="high"/>
 <tile id="14" type="high"/>
 <tile id="15" type="high"/>
 <tile id="17" type="high"/>
 <tile id="18" type="high"/>
 <tile id="19" type="high"/>
 <tile id="20" type="high"/>
 <tile id="21" type="high"/>
 <tile id="22" type="high"/>
 <tile id="23" type="high"/>
 <tile id="25" type="high"/>
 <tile id="26" type="high"/>
 <tile id="27" type="high"/>
 <tile id="28" type="high"/>
 <tile id="29" type="high"/>
 <tile id="30" type="high"/>
 <tile id="31" type="high"/>
 <tile id="33" type="high"/>
 <tile id="34" type="high"/>
 <tile id="35" type="high"/>
 <tile id="36" type="high"/>
 <tile id="37" type="high"/>
 <tile id="38" type="high"/>
 <tile id="39" type="high"/>
 <tile id="41" type="high"/>
 <tile id="42" type="high"/>
 <tile id="43" type="high"/>
 <tile id="44" type="high"/>
 <tile id="45" type="high"/>
 <tile id="46" type="high"/>
 <tile id="47" type="high"/>
</tileset>
