<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="moose1-347x192" tilewidth="347" tileheight="192" tilecount="150" columns="30">
 <image source="C:/kyrgyz_epos_game/assets/tiles/sprites/players/moose1-347x192.png" width="10410" height="960"/>
 <tile id="0" type="moose"/>
 <tile id="1" type="moose"/>
 <tile id="2" type="moose"/>
 <tile id="3" type="moose"/>
 <tile id="4" type="moose"/>
 <tile id="5" type="moose"/>
 <tile id="6" type="moose"/>
 <tile id="7" type="moose"/>
 <tile id="8" type="moose"/>
 <tile id="9" type="moose"/>
 <tile id="10" type="moose"/>
 <tile id="11" type="moose"/>
 <tile id="12" type="moose"/>
 <tile id="13" type="moose"/>
 <tile id="14" type="moose"/>
 <tile id="15" type="moose"/>
 <tile id="16" type="moose"/>
 <tile id="17" type="moose"/>
 <tile id="18" type="moose"/>
 <tile id="19" type="moose"/>
 <tile id="20" type="moose"/>
 <tile id="21" type="moose"/>
 <tile id="22" type="moose"/>
 <tile id="23" type="moose"/>
 <tile id="24" type="moose"/>
 <tile id="25" type="moose"/>
 <tile id="26" type="moose"/>
 <tile id="27" type="moose"/>
 <tile id="28" type="moose"/>
 <tile id="29" type="moose"/>
 <tile id="30" type="moose"/>
 <tile id="31" type="moose"/>
 <tile id="32" type="moose"/>
 <tile id="33" type="moose"/>
 <tile id="34" type="moose"/>
 <tile id="35" type="moose"/>
 <tile id="36" type="moose"/>
 <tile id="37" type="moose"/>
 <tile id="38" type="moose"/>
 <tile id="39" type="moose"/>
 <tile id="40" type="moose"/>
 <tile id="41" type="moose"/>
 <tile id="42" type="moose"/>
 <tile id="43" type="moose"/>
 <tile id="44" type="moose"/>
 <tile id="45" type="moose"/>
 <tile id="46" type="moose"/>
 <tile id="47" type="moose"/>
 <tile id="48" type="moose"/>
 <tile id="49" type="moose"/>
 <tile id="50" type="moose"/>
 <tile id="51" type="moose"/>
 <tile id="52" type="moose"/>
 <tile id="53" type="moose"/>
 <tile id="54" type="moose"/>
 <tile id="55" type="moose"/>
 <tile id="56" type="moose"/>
 <tile id="57" type="moose"/>
 <tile id="58" type="moose"/>
 <tile id="59" type="moose"/>
 <tile id="60" type="moose"/>
 <tile id="61" type="moose"/>
 <tile id="62" type="moose"/>
 <tile id="63" type="moose"/>
 <tile id="64" type="moose"/>
 <tile id="65" type="moose"/>
 <tile id="66" type="moose"/>
 <tile id="67" type="moose"/>
 <tile id="68" type="moose"/>
 <tile id="69" type="moose"/>
 <tile id="70" type="moose"/>
 <tile id="71" type="moose"/>
 <tile id="72" type="moose"/>
 <tile id="73" type="moose"/>
 <tile id="74" type="moose"/>
 <tile id="75" type="moose"/>
 <tile id="76" type="moose"/>
 <tile id="77" type="moose"/>
 <tile id="78" type="moose"/>
 <tile id="79" type="moose"/>
 <tile id="80" type="moose"/>
 <tile id="81" type="moose"/>
 <tile id="82" type="moose"/>
 <tile id="83" type="moose"/>
 <tile id="84" type="moose"/>
 <tile id="85" type="moose"/>
 <tile id="86" type="moose"/>
 <tile id="87" type="moose"/>
 <tile id="88" type="moose"/>
 <tile id="89" type="moose"/>
 <tile id="90" type="moose"/>
 <tile id="91" type="moose"/>
 <tile id="92" type="moose"/>
 <tile id="93" type="moose"/>
 <tile id="94" type="moose"/>
 <tile id="95" type="moose"/>
 <tile id="96" type="moose"/>
 <tile id="97" type="moose"/>
 <tile id="98" type="moose"/>
 <tile id="99" type="moose"/>
 <tile id="100" type="moose"/>
 <tile id="101" type="moose"/>
 <tile id="102" type="moose"/>
 <tile id="103" type="moose"/>
 <tile id="104" type="moose"/>
 <tile id="105" type="moose"/>
 <tile id="106" type="moose"/>
 <tile id="107" type="moose"/>
 <tile id="108" type="moose"/>
 <tile id="109" type="moose"/>
 <tile id="110" type="moose"/>
 <tile id="111" type="moose"/>
 <tile id="112" type="moose"/>
 <tile id="113" type="moose"/>
 <tile id="114" type="moose"/>
 <tile id="115" type="moose"/>
 <tile id="116" type="moose"/>
 <tile id="117" type="moose"/>
 <tile id="118" type="moose"/>
 <tile id="119" type="moose"/>
 <tile id="120" type="moose"/>
 <tile id="121" type="moose"/>
 <tile id="122" type="moose"/>
 <tile id="123" type="moose"/>
 <tile id="124" type="moose"/>
 <tile id="125" type="moose"/>
 <tile id="126" type="moose"/>
 <tile id="127" type="moose"/>
 <tile id="128" type="moose"/>
 <tile id="129" type="moose"/>
 <tile id="130" type="moose"/>
 <tile id="131" type="moose"/>
 <tile id="132" type="moose"/>
 <tile id="133" type="moose"/>
 <tile id="134" type="moose"/>
 <tile id="135" type="moose"/>
 <tile id="136" type="moose"/>
 <tile id="137" type="moose"/>
 <tile id="138" type="moose"/>
 <tile id="139" type="moose"/>
 <tile id="140" type="moose"/>
 <tile id="141" type="moose"/>
 <tile id="142" type="moose"/>
 <tile id="143" type="moose"/>
 <tile id="144" type="moose"/>
 <tile id="145" type="moose"/>
 <tile id="146" type="moose"/>
 <tile id="147" type="moose"/>
 <tile id="148" type="moose"/>
 <tile id="149" type="moose"/>
</tileset>
