<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="Stone-224x192" tilewidth="224" tileheight="192" tilecount="85" columns="17">
 <image source="tiles/sprites/players/Stone-224x192.png" width="3808" height="960"/>
 <tile id="0" type="ggolem"/>
 <tile id="1" type="ggolem"/>
 <tile id="2" type="ggolem"/>
 <tile id="3" type="ggolem"/>
 <tile id="4" type="ggolem"/>
 <tile id="5" type="ggolem"/>
 <tile id="6" type="ggolem"/>
 <tile id="7" type="ggolem"/>
 <tile id="8" type="ggolem"/>
 <tile id="9" type="ggolem"/>
 <tile id="10" type="ggolem"/>
 <tile id="11" type="ggolem"/>
 <tile id="12" type="ggolem"/>
 <tile id="13" type="ggolem"/>
 <tile id="14" type="ggolem"/>
 <tile id="15" type="ggolem"/>
 <tile id="16" type="ggolem"/>
 <tile id="17" type="ggolem"/>
 <tile id="18" type="ggolem"/>
 <tile id="19" type="ggolem"/>
 <tile id="20" type="ggolem"/>
 <tile id="21" type="ggolem"/>
 <tile id="22" type="ggolem"/>
 <tile id="23" type="ggolem"/>
 <tile id="24" type="ggolem"/>
 <tile id="25" type="ggolem"/>
 <tile id="26" type="ggolem"/>
 <tile id="27" type="ggolem"/>
 <tile id="28" type="ggolem"/>
 <tile id="29" type="ggolem"/>
 <tile id="30" type="ggolem"/>
 <tile id="31" type="ggolem"/>
 <tile id="32" type="ggolem"/>
 <tile id="33" type="ggolem"/>
 <tile id="34" type="ggolem"/>
 <tile id="35" type="ggolem"/>
 <tile id="36" type="ggolem"/>
 <tile id="37" type="ggolem"/>
 <tile id="38" type="ggolem"/>
 <tile id="39" type="ggolem"/>
 <tile id="40" type="ggolem"/>
 <tile id="41" type="ggolem"/>
 <tile id="42" type="ggolem"/>
 <tile id="43" type="ggolem"/>
 <tile id="44" type="ggolem"/>
 <tile id="45" type="ggolem"/>
 <tile id="46" type="ggolem"/>
 <tile id="47" type="ggolem"/>
 <tile id="48" type="ggolem"/>
 <tile id="49" type="ggolem"/>
 <tile id="50" type="ggolem"/>
 <tile id="51" type="ggolem"/>
 <tile id="52" type="ggolem"/>
 <tile id="53" type="ggolem"/>
 <tile id="54" type="ggolem"/>
 <tile id="55" type="ggolem"/>
 <tile id="56" type="ggolem"/>
 <tile id="57" type="ggolem"/>
 <tile id="58" type="ggolem"/>
 <tile id="59" type="ggolem"/>
 <tile id="60" type="ggolem"/>
 <tile id="61" type="ggolem"/>
 <tile id="62" type="ggolem"/>
 <tile id="63" type="ggolem"/>
 <tile id="64" type="ggolem"/>
 <tile id="65" type="ggolem"/>
 <tile id="66" type="ggolem"/>
 <tile id="67" type="ggolem"/>
 <tile id="68" type="ggolem"/>
 <tile id="69" type="ggolem"/>
 <tile id="70" type="ggolem"/>
 <tile id="71" type="ggolem"/>
 <tile id="72" type="ggolem"/>
 <tile id="73" type="ggolem"/>
 <tile id="74" type="ggolem"/>
 <tile id="75" type="ggolem"/>
 <tile id="76" type="ggolem"/>
 <tile id="77" type="ggolem"/>
 <tile id="78" type="ggolem"/>
 <tile id="79" type="ggolem"/>
 <tile id="80" type="ggolem"/>
 <tile id="81" type="ggolem"/>
 <tile id="82" type="ggolem"/>
 <tile id="83" type="ggolem"/>
 <tile id="84" type="ggolem"/>
</tileset>
